//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoInfoSystem.MyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AutoInfoSystem.MyServiceReference.HelloWorldResponse HelloWorld(AutoInfoSystem.MyServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 QueryInfoFromDBResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryInfoFromDB", ReplyAction="*")]
        AutoInfoSystem.MyServiceReference.QueryInfoFromDBResponse QueryInfoFromDB(AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSql 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecSqlCmd", ReplyAction="*")]
        AutoInfoSystem.MyServiceReference.ExecSqlCmdResponse ExecSqlCmd(AutoInfoSystem.MyServiceReference.ExecSqlCmdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AutoInfoSystem.MyServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AutoInfoSystem.MyServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoInfoSystem.MyServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AutoInfoSystem.MyServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryInfoFromDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryInfoFromDB", Namespace="http://tempuri.org/", Order=0)]
        public AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequestBody Body;
        
        public QueryInfoFromDBRequest() {
        }
        
        public QueryInfoFromDBRequest(AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class QueryInfoFromDBRequestBody {
        
        public QueryInfoFromDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryInfoFromDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryInfoFromDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoInfoSystem.MyServiceReference.QueryInfoFromDBResponseBody Body;
        
        public QueryInfoFromDBResponse() {
        }
        
        public QueryInfoFromDBResponse(AutoInfoSystem.MyServiceReference.QueryInfoFromDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryInfoFromDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryInfoFromDBResult;
        
        public QueryInfoFromDBResponseBody() {
        }
        
        public QueryInfoFromDBResponseBody(string QueryInfoFromDBResult) {
            this.QueryInfoFromDBResult = QueryInfoFromDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecSqlCmdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecSqlCmd", Namespace="http://tempuri.org/", Order=0)]
        public AutoInfoSystem.MyServiceReference.ExecSqlCmdRequestBody Body;
        
        public ExecSqlCmdRequest() {
        }
        
        public ExecSqlCmdRequest(AutoInfoSystem.MyServiceReference.ExecSqlCmdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecSqlCmdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSql;
        
        public ExecSqlCmdRequestBody() {
        }
        
        public ExecSqlCmdRequestBody(string strSql) {
            this.strSql = strSql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecSqlCmdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecSqlCmdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoInfoSystem.MyServiceReference.ExecSqlCmdResponseBody Body;
        
        public ExecSqlCmdResponse() {
        }
        
        public ExecSqlCmdResponse(AutoInfoSystem.MyServiceReference.ExecSqlCmdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecSqlCmdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ExecSqlCmdResult;
        
        public ExecSqlCmdResponseBody() {
        }
        
        public ExecSqlCmdResponseBody(int ExecSqlCmdResult) {
            this.ExecSqlCmdResult = ExecSqlCmdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WebServiceSoapChannel : AutoInfoSystem.MyServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AutoInfoSystem.MyServiceReference.WebServiceSoap>, AutoInfoSystem.MyServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoInfoSystem.MyServiceReference.HelloWorldResponse AutoInfoSystem.MyServiceReference.WebServiceSoap.HelloWorld(AutoInfoSystem.MyServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AutoInfoSystem.MyServiceReference.HelloWorldRequest inValue = new AutoInfoSystem.MyServiceReference.HelloWorldRequest();
            inValue.Body = new AutoInfoSystem.MyServiceReference.HelloWorldRequestBody();
            AutoInfoSystem.MyServiceReference.HelloWorldResponse retVal = ((AutoInfoSystem.MyServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoInfoSystem.MyServiceReference.QueryInfoFromDBResponse AutoInfoSystem.MyServiceReference.WebServiceSoap.QueryInfoFromDB(AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequest request) {
            return base.Channel.QueryInfoFromDB(request);
        }
        
        public string QueryInfoFromDB() {
            AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequest inValue = new AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequest();
            inValue.Body = new AutoInfoSystem.MyServiceReference.QueryInfoFromDBRequestBody();
            AutoInfoSystem.MyServiceReference.QueryInfoFromDBResponse retVal = ((AutoInfoSystem.MyServiceReference.WebServiceSoap)(this)).QueryInfoFromDB(inValue);
            return retVal.Body.QueryInfoFromDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoInfoSystem.MyServiceReference.ExecSqlCmdResponse AutoInfoSystem.MyServiceReference.WebServiceSoap.ExecSqlCmd(AutoInfoSystem.MyServiceReference.ExecSqlCmdRequest request) {
            return base.Channel.ExecSqlCmd(request);
        }
        
        public int ExecSqlCmd(string strSql) {
            AutoInfoSystem.MyServiceReference.ExecSqlCmdRequest inValue = new AutoInfoSystem.MyServiceReference.ExecSqlCmdRequest();
            inValue.Body = new AutoInfoSystem.MyServiceReference.ExecSqlCmdRequestBody();
            inValue.Body.strSql = strSql;
            AutoInfoSystem.MyServiceReference.ExecSqlCmdResponse retVal = ((AutoInfoSystem.MyServiceReference.WebServiceSoap)(this)).ExecSqlCmd(inValue);
            return retVal.Body.ExecSqlCmdResult;
        }
    }
}
